# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

project: ''
title: ''
author: Tristan Boin
logo: "_static/logo.svg"
copyright: "2026"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath

html:
  static_path: ["_static"]
  use_relative_urls: true
  theme:
    name: furo
  favicon: "_static/favicon.ico"

sphinx:
  config:
    html_theme: furo
    html_static_path:
      - _static
    html_css_files:
      - force-light.css
    html_js_files:
      - force-light.js
    html_show_sphinx: false
    templates_path:
      - _templates
    pygments_style: friendly
    pygments_dark_style: friendly
  extra_extensions:
    - sphinx_inline_tabs