import inspect
import textwrap
from pathlib import Path
import importlib.util

import matplotlib.pyplot as plt

# ---------------- CONFIG ----------------

PACKAGE_NAME = "package"
PACKAGE_ROOT = Path(__file__).parent

ANIMATIONS_FILE = PACKAGE_ROOT / "animations.py"
OUT_FILE = PACKAGE_ROOT / "_generated_api.py"

ANIMATION_EXTRA_PARAMS = [
    ("duration", None),
    ("delay", 0),
    ("easing", None),
    ("axis", None),
]

# --------------------------------------


def load_animations_module():
    spec = importlib.util.spec_from_file_location(
        f"{PACKAGE_NAME}._animations_gen", ANIMATIONS_FILE
    )
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module

def extend_signature_with_extra(sig: inspect.Signature) -> inspect.Signature:
    existing_names = set(sig.parameters.keys())

    normal_params = []
    var_positional = None
    keyword_only = []
    var_keyword = None

    for p in sig.parameters.values():
        if p.kind in [inspect.Parameter.POSITIONAL_ONLY, inspect.Parameter.POSITIONAL_OR_KEYWORD]:
            normal_params.append(p)
        elif p.kind == inspect.Parameter.VAR_POSITIONAL:
            var_positional = p
        elif p.kind == inspect.Parameter.KEYWORD_ONLY:
            keyword_only.append(p)
        elif p.kind == inspect.Parameter.VAR_KEYWORD:
            var_keyword = p
    
    extras_to_add = []
    for name, default in ANIMATION_EXTRA_PARAMS:
        if name not in existing_names:
            extras_to_add.append(inspect.Parameter(name, inspect.Parameter.POSITIONAL_OR_KEYWORD, default=default))

    new_params = normal_params + extras_to_add
    if var_positional:
        new_params.append(var_positional)
    new_params.extend(keyword_only)
    if var_keyword:
        new_params.append(var_keyword)

    return sig.replace(parameters=new_params)

def build_call_from_signature(sig: inspect.Signature) -> str:
    parts = []
    for p in sig.parameters.values():
        if p.kind in [inspect.Parameter.POSITIONAL_ONLY, inspect.Parameter.POSITIONAL_OR_KEYWORD]:
            parts.append(p.name)
        elif p.kind == inspect.Parameter.VAR_POSITIONAL:
            parts.append(f"*{p.name}")
        elif p.kind == inspect.Parameter.KEYWORD_ONLY:
            parts.append(f"{p.name}={p.name}")
        elif p.kind == inspect.Parameter.VAR_KEYWORD:
            parts.append(f"**{p.name}")
    return ", ".join(parts)


def insert_extra_doc(doc: str) -> str:
    extra_doc = """
duration : float
    Duration of the animation
delay : float, default=0
    Delay before starting
easing : callable, optional
    Easing function
axis : matplotlib.axes.Axes, optional
    Axis to plot on
"""

    if "Parameters" in doc:
        parts = doc.split("Parameters", 1)
        header = parts[0] + "Parameters"
        rest = parts[1]

        if "\n\n" in rest:
            param_body, remainder = rest.split("\n\n", 1)
            doc = header + param_body + "\n" + extra_doc + "\n\n" + remainder
        else:
            doc = header + rest + "\n" + extra_doc
    else:
        doc = doc + "\n\nParameters\n----------\n" + extra_doc

    return textwrap.indent(doc, "    ")


def main():
    animations = load_animations_module()

    public_names = [
        name for name in dir(animations)
        if not name.startswith("_")
        and callable(getattr(animations, name))
    ]

    lines = [
        "# AUTO-GENERATED FILE — DO NOT EDIT\n",
        "# Generated by generate_doc_api.py\n\n",
        "from . import animations as _impl\n\n",
        f"__all__ = {public_names!r}\n\n",
    ]

    for name in public_names:
        print(name)
        impl = getattr(animations, name)

        if hasattr(plt, name):
            source_fn = getattr(plt, name)
            doc = inspect.getdoc(source_fn) or ""
        else:
            source_fn = impl
            doc = ""

        sig = inspect.signature(source_fn)
        sig = extend_signature_with_extra(sig)
        call = build_call_from_signature(sig)
        doc = insert_extra_doc(doc)

        lines.append(f"def {name}{sig}:\n")
        lines.append('    """\n')
        lines.append(f"{doc}\n")
        lines.append('    """\n')
        lines.append(f"    return _impl.{name}({call})\n\n")

    OUT_FILE.write_text("".join(lines), encoding="utf-8")
    print(f"Generated _generated_api.py with {len(public_names)} functions/classes.")

if __name__ == "__main__":
    main()
